### ISSUE TITLE
Include Camera RAW

### ISSUE THREAD

**Issue by user82622** [gmanka-flatpaks/com.adobe.photoshop2021#3]
It would be really handy to include the camera raw filter so Photoshop is capable of handling all kinds of raw files. 

curl -L "https://download.adobe.com/pub/adobe/photoshop/cameraraw/win/12.x/CameraRaw_12_2_1.exe" > CameraRaw_12_2_1.exe WINEPREFIX=/Path/To/Your/Photoshop/Install/Adobe-Photoshop wine CameraRaw_12_2_1.exe

https://github.com/LinSoftWin/Photoshop-CC2022-Linux

**Comment by gmankab** [comment]
i'l try to include it later

feel free to open pull request

**Comment by user82622** [comment]
I sadly failed until now, the problem is that I ether have to include all unpacked data in the photoshop2021 tar files or adding another module, but I run into the problem that the CameraRaw installer wants to spawn a window and I haven't figured out how to get the install going in the build without the installer GUI. 

```yml
name: cameraraw
buildsystem: simple
sources:
  - type: file
    path: CameraRaw_12_2_1.exe
build-commands:
  - WINEPREFIX=/app/photoshop2021 wine64 CameraRaw_12_2_1.exe 
```
